ucsm_serviceprofiletemplate{'serviceprofiletemplate':
policy_name            => 'pretest',
type                   => 'updating-template',
storage_profile_name   => 'Docker-storage',
vnic_name              => 'NewPuppetvnic6',
vnic_template_name     => 'Docker-Vnic',
adapter_profile_name   => 'Linux',
vnic_order             => '1',
server_pool_name       => 'puppettest',
local_disk_policy_name => 'diskconfigp1',
ident_pool_name        => 'uuidPool1',
host_fw_policy_name    => 'puppetpackage',
boot_policy_name       => 'utility',
bios_profile_name      => 'paramtest',
maint_policy_name      => 'newmaintenance',
mgmt_ip_address        => 'newippool',
ip                     => '172.28.224.121',
username               => 'admin',
password               => 'password',
state                  => 'present',
}
